# Generated by Django 5.0.1 on 2024-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
